# А ты проверяла эту задачу? По заданию просят вывести 9 строк, но у тебя всего лишь 7
s = input()
print(s[2])
print(s[-2])
print(s[:5])
print(s[:-2])
print(s[::2])
print(s[1::2])
print(s[::-1])
print(s[::-2])
print(len(s))
